spring:
  application:
    name: shopnow
  datasource:
    url: jdbc:h2:mem:shopnow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
